import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigate from "./components/Navigate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("-called Home Component-");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <Navigate />
        </header>
        <div className="container">{children}</div>
        <h1 className="h1 bg-amber-600 p-10">Footer</h1>
      </body>
    </html>
  );
}
